header:
  - name: Accueil
    pageRef: /
    weight: 1
  - name: Photos
    url: https://la-binocle.com
    weight: 4
  - name: A propos
    pageRef: /a-propos
    weight: 5
footer:
  - name: Signets
    pageRef: /signets
    weight: 1
  - name: Notes
    pageRef: /notes
    weight: 2
  - name: Contact
    identifier: mailto
    weight: 3
  - name: Mentions légales
    pageRef: /mentions-legales
    weight: 4
  - name: Politique de confidentialité
    pageRef: /politique-de-confidentialite
    weight: 5
