header:
  - name: Home
    pageRef: /
    weight: 1
  - name: Photos
    url: https://la-binocle.com
    weight: 2
  - name: About
    pageRef: /a-propos
    weight: 3
footer:
  - name: Bookmarks
    pageRef: /signets
    weight: 1
  - name: Contact
    identifier: mailto
    weight: 2
  - name: Legal notice
    pageRef: /mentions-legales
    weight: 3
  - name: Privacy policy
    pageRef: /politique-de-confidentialite
    weight: 4
