header:
  - name: Accueil
    pageRef: /
    weight: 1
  - name: A propos
    pageRef: /a-propos
    weight: 2
  - name: Photos
    url: https://la-binocle.com
    weight: 3
footer:
  - name: Contact
    identifier: mailto
    weight: 1
  - name: Mentions légales
    pageRef: /mentions-legales
    weight: 2
  - name: Politique de confidentialité
    pageRef: /politique-de-confidentialite
    weight: 3
