contact_email: contact@clementbiron.com
mastodon: 
  url: https://mastodon.social/@clementbiron
  username: "@clementbiron@mastodon.social"
github:
  url: https://github.com/clementbiron
linkedin:
  url: https://www.linkedin.com/in/clementbiron/
